'use client'
import { useEffect, useState } from 'react'
import { PageLayout } from '@/components/PageLayout'

const API = process.env.NEXT_PUBLIC_API_URL

function tryParse(s: string) {
  try { return JSON.parse(s) } catch { return null }
}

export default function AIReportsPage() {
  const [paths,   setPaths]   = useState<any[]>([])
  const [score,   setScore]   = useState<number|null>(null)
  const [loading, setLoading] = useState(true)

  useEffect(() => {
    fetch(`${API}/dashboard/me`)
      .then(r => r.json())
      .then(d => {
        setPaths(d.attack_paths || [])
        setScore(d.score ?? null)
        setLoading(false)
      })
      .catch(() => setLoading(false))
  }, [])

  const narrated = paths.filter(p => p.ai_narrative)

  return (
    <PageLayout title="AI Reports" subtitle="Plain-English security analysis generated by Claude AI">

      {loading && <div style={{ color: '#37637a', fontSize: 13, textAlign: 'center', paddingTop: 60 }}>Loading...</div>}

      {!loading && (
        <>
          {/* Executive summary */}
          <div style={{ background: '#0a1929', border: '1px solid #1a2d45', borderLeft: '4px solid #4fc3f7', borderRadius: 8, padding: 20, marginBottom: 20 }}>
            <div style={{ fontSize: 12, color: '#4fc3f7', textTransform: 'uppercase', letterSpacing: '.7px', marginBottom: 10 }}>
              Executive Summary
            </div>
            <p style={{ fontSize: 13, color: '#b0bec5', lineHeight: 1.7, margin: 0 }}>
              {score !== null
                ? `Your AWS account has a security score of ${score.toFixed(0)}/100. `
                : ''
              }
              {paths.length === 0
                ? 'No attack paths were detected. Your account appears to have a strong security posture.'
                : `Canopy detected ${paths.length} attack path${paths.length > 1 ? 's' : ''}, including ${paths.filter(p=>p.exploitability==='CRITICAL').length} critical chain${paths.filter(p=>p.exploitability==='CRITICAL').length !== 1 ? 's' : ''} that could allow an attacker to gain administrative control of your cloud environment. Immediate remediation is recommended.`
              }
            </p>
          </div>

          {/* Individual AI narratives */}
          {narrated.length === 0 && (
            <div style={{ textAlign: 'center', paddingTop: 40 }}>
              <i className="ti ti-robot" style={{ fontSize: 40, color: '#37637a', display: 'block', marginBottom: 12 }} />
              <div style={{ color: '#455a64', fontSize: 13 }}>
                {paths.length === 0
                  ? 'Run a scan to generate AI reports.'
                  : 'AI narratives are generated for CRITICAL paths. No CRITICAL paths were found in this scan.'
                }
              </div>
            </div>
          )}

          <div style={{ display: 'flex', flexDirection: 'column', gap: 16 }}>
            {narrated.map((path, i) => {
              const nar = tryParse(path.ai_narrative)
              if (!nar) return null
              return (
                <div key={i} style={{ background: '#0a1929', border: '1px solid #1a2d45', borderRadius: 8, overflow: 'hidden' }}>
                  {/* Header */}
                  <div style={{ background: '#0f1a2a', padding: '14px 18px', borderBottom: '1px solid #1a2d45', display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
                    <div style={{ display: 'flex', alignItems: 'center', gap: 10 }}>
                      <span style={{ fontSize: 10, padding: '3px 10px', borderRadius: 4, background: '#1a0a0a', color: '#ef5350', fontWeight: 500 }}>
                        {path.exploitability}
                      </span>
                      <span style={{ fontSize: 14, fontWeight: 500, color: '#e1f5fe' }}>
                        {nar.headline || `Attack path to ${path.target_name}`}
                      </span>
                    </div>
                    <div style={{ fontSize: 11, color: '#455a64' }}>
                      Score {path.score?.toFixed(2)} · Blast {path.blast_radius?.toFixed(0)}%
                    </div>
                  </div>

                  {/* Body */}
                  <div style={{ padding: 18, display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 16 }}>
                    <div>
                      <div style={{ fontSize: 10, color: '#37637a', textTransform: 'uppercase', letterSpacing: '.7px', marginBottom: 6 }}>What Happened</div>
                      <p style={{ fontSize: 12, color: '#b0bec5', lineHeight: 1.7, margin: 0 }}>{nar.story}</p>
                    </div>
                    <div>
                      <div style={{ fontSize: 10, color: '#37637a', textTransform: 'uppercase', letterSpacing: '.7px', marginBottom: 6 }}>Business Impact</div>
                      <p style={{ fontSize: 12, color: '#ff9800', lineHeight: 1.7, margin: 0 }}>{nar.business_impact}</p>
                    </div>
                    <div>
                      <div style={{ fontSize: 10, color: '#37637a', textTransform: 'uppercase', letterSpacing: '.7px', marginBottom: 6 }}>Recommended Fix</div>
                      <p style={{ fontSize: 12, color: '#4caf50', lineHeight: 1.7, margin: 0 }}>
                        {nar.fix}
                        {nar.fix_time && <span style={{ color: '#37637a', marginLeft: 6 }}>({nar.fix_time})</span>}
                      </p>
                    </div>
                    <div>
                      <div style={{ fontSize: 10, color: '#37637a', textTransform: 'uppercase', letterSpacing: '.7px', marginBottom: 6 }}>Attacker Profile</div>
                      <p style={{ fontSize: 12, color: '#b0bec5', lineHeight: 1.7, margin: 0 }}>
                        Difficulty: <span style={{ color: '#e1f5fe' }}>{nar.attacker_difficulty}</span>
                        <br />
                        Time to exploit: <span style={{ color: '#ef5350' }}>{nar.time_to_exploit}</span>
                      </p>
                    </div>
                  </div>

                  {/* Hop chain */}
                  <div style={{ padding: '12px 18px', borderTop: '1px solid #1a2d45', display: 'flex', gap: 6, flexWrap: 'wrap', alignItems: 'center' }}>
                    {path.hops?.map((h: any, hi: number) => (
                      <span key={hi} style={{ display: 'flex', alignItems: 'center', gap: 6 }}>
                        <span style={{ fontSize: 10, padding: '2px 8px', background: '#0f2236', color: '#90caf9', borderRadius: 4 }}>{h.source_name}</span>
                        <i className="ti ti-arrow-right" style={{ fontSize: 10, color: '#37637a' }} />
                        {hi === path.hops.length - 1 && (
                          <span style={{ fontSize: 10, padding: '2px 8px', background: '#1a0a0a', color: '#ef5350', borderRadius: 4 }}>{h.target_name}</span>
                        )}
                      </span>
                    ))}
                  </div>
                </div>
              )
            })}
          </div>
        </>
      )}
    </PageLayout>
  )
}